/*
    https://projecteuler.net/problem=2
       
    Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

*/

#include <iostream>

int main()
{
    int upperLimit = 4000000;
    int oldNumber = 1;
    int newNumber = 2;
    int totalSum = 2;
    int evenSum = 2;

    std::cout << oldNumber << std::endl;
    std::cout << newNumber << std::endl;
    
    while (totalSum < upperLimit)
    {
        
        totalSum = oldNumber + newNumber;
        oldNumber = newNumber;        
        newNumber = totalSum;     

        std::cout << newNumber << std::endl;

        if (totalSum % 2 == 0)
        {
            evenSum += totalSum;
        }

        if (totalSum >= upperLimit)
        {
            break;
        }
    }

    std::cout << std::endl;

    std::cout << "The Sum of the even-valued terms is " << evenSum << std::endl;

    return 0;
}